# Generated by Django 5.2 on 2025-04-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
