# Generated by Django 5.2 on 2025-04-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_votes', models.IntegerField(default=3)),
                ('title_of_the_page', models.CharField(default='Vote for Your Favorite Photos', max_length=100)),
                ('description_of_the_page', models.TextField(default='Vote for your favorite photos and show your love for them.')),
            ],
        ),
    ]
